name = "easyclean"
main = ".open-next/worker.js"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]
account_id = "7b30f143954b2610fd7613a7c0a3d87e"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "easyclean-db"
database_id = "fec70c95-c3af-4632-b772-91d40fdaaa75"
migrations_dir = "drizzle/migrations"

[vars]
NEXT_PUBLIC_APP_URL = "https://easyclean.cerqueirapedro275.workers.dev"
BETTER_AUTH_URL = "https://easyclean.cerqueirapedro275.workers.dev"
